"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { topics } from "./topics/data";
const focus = ["Pediatric ophthalmology", "Strabismus and squint evaluation", "Lazy eye and amblyopia care", "Childhood glasses and refraction", "Retinopathy of prematurity screening", "Pediatric cataract", "Adult strabismus and double vision", "Patient education for families"];
const credentials = ["Fellowship in Pediatric Ophthalmology and Strabismus Surgery, Lumbini Eye Institute and Research Centre, 2024", "MD Ophthalmology, Nepal Eye Hospital, National Academy of Medical Sciences, 2019", "MBBS and Internship, College of Medical Sciences, Bharatpur, Kathmandu University, 2015", "Lifetime member, Nepal Medical Association", "Lifetime member, Nepal Ophthalmic Society", "Lifetime member, Nepal Pediatric Ophthalmology and Strabismus Society"];
export default function Home(){
 const [theme,setTheme]=useState("light"); const [lang,setLang]=useState<"en"|"np">("en");
 useEffect(()=>{const saved=localStorage.getItem("theme")||"light"; setTheme(saved); document.documentElement.dataset.theme=saved},[]);
 const toggle=()=>{const next=theme==="light"?"dark":"light"; setTheme(next); document.documentElement.dataset.theme=next; localStorage.setItem("theme",next)};
 return <main><header className="site-header"><Link className="brand" href="/"><span className="brand-mark">TD</span><span><strong>Dr Toshika Dahal</strong><small>Pediatric Ophthalmologist</small></span></Link><nav className="desktop-nav"><a href="#focus">Focus</a><a href="#topics">Eye topics</a><a href="#credentials">Credentials</a><a href="#visit">Visit</a><Link href="/contact">Contact</Link></nav><div className="header-actions"><button onClick={()=>setLang(lang==="en"?"np":"en")}>{lang==="en"?"à¤¨à¥‡à¤ªà¤¾à¤²à¥€":"English"}</button><button onClick={toggle}>{theme==="light"?"Dark":"Light"}</button></div></header>
 <section className="hero"><div><p className="eyebrow">Pediatric ophthalmology and strabismus care</p><h1>{lang==="en"?"Clear eye care for children, families, and adults with squint.":"à¤¬à¤¾à¤²à¤¬à¤¾à¤²à¤¿à¤•à¤¾, à¤ªà¤°à¤¿à¤µà¤¾à¤° à¤° à¤Ÿà¥‡à¤¢à¥‹ à¤†à¤à¤–à¤¾à¤•à¥‹ à¤¸à¤®à¤¸à¥à¤¯à¤¾ à¤­à¤à¤•à¤¾ à¤¬à¤¿à¤°à¤¾à¤®à¥€à¤•à¤¾ à¤²à¤¾à¤—à¤¿ à¤¸à¥à¤ªà¤·à¥à¤Ÿ à¤†à¤à¤–à¤¾ à¤¸à¥‡à¤µà¤¾à¥¤"}</h1><p className="lead">Dr Toshika Dahal is a Pediatric Ophthalmologist and Strabismus Surgeon at Lumbini Eye Institute, Bhairahawa, Nepal. Her work focuses on child eye examination, squint, amblyopia, glasses in children, premature baby retina screening, and adult strabismus.</p><div className="hero-actions"><a className="primary-button" href="tel:+9779841740018">Call for appointment</a><Link className="secondary-button" href="/topics">Read eye topics</Link></div><div className="quick-facts"><div><b>Fellowship</b><span>Pediatric Ophthalmology and Strabismus</span></div><div><b>Current work</b><span>Lumbini Eye Institute, Bhairahawa</span></div><div><b>For families</b><span>Simple guidance before and after visit</span></div></div></div><div className="hero-media"><img src="/images/dr-toshika-dahal-portrait.jpg" alt="Dr Toshika Dahal"/></div></section>
 <section id="focus" className="section"><div className="section-heading"><p className="eyebrow">Clinical focus</p><h2>Ophthalmology care designed for children and families</h2><p>The content is structured like strong ophthalmology websites with a clear profile, focused services, patient education, red flags, and appointment guidance.</p></div><div className="focus-grid">{focus.map(x=><article className="focus-card" key={x}><span>âœ“</span><h3>{x}</h3><p>Clear assessment, practical counseling, and follow up planning based on age and visual risk.</p></article>)}</div></section>
 <section id="topics" className="section soft-section"><div className="section-heading"><p className="eyebrow">Patient education</p><h2>Common eye problems explained simply</h2><p>Each topic page explains signs, clinic evaluation, and warning signs that need urgent care.</p></div><div className="topic-grid">{topics.slice(0,8).map(t=><Link className="topic-card" href={`/topics/${t.slug}`} key={t.slug}><span className="topic-icon">{t.icon}</span><h3>{lang==="en"?t.title:t.nepaliTitle}</h3><p>{t.summary}</p><small>Read more</small></Link>)}</div><div className="center-action"><Link className="secondary-button" href="/topics">View all eye topics</Link></div></section>
 <section id="credentials" className="section split"><div><p className="eyebrow">Credentials</p><h2>Education, fellowship, and memberships</h2><p>Dr Toshika completed fellowship training in Pediatric Ophthalmology and Strabismus Surgery after MD Ophthalmology and MBBS training.</p><Link className="secondary-button" href="/about">Full profile</Link></div><div className="timeline">{credentials.map((x,i)=><div className="timeline-item" key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></div>)}</div></section>
 <section id="visit" className="section visit-section"><div className="visit-card"><p className="eyebrow">Visit and contact</p><h2>Lumbini Eye Institute, Bhairahawa</h2><p>Call before visiting to confirm OPD timing, appointment availability, and whether your child needs dilating drops during the visit.</p><div className="visit-actions"><a className="primary-button" href="tel:+9779841740018">+977 9841740018</a><a className="secondary-button" href="mailto:toshikadahal2047@gmail.com">Email</a></div></div><div className="warning-card"><h3>Urgent eye warning signs</h3><ul><li>Sudden vision loss</li><li>Severe eye pain or light sensitivity</li><li>White reflex in a child photo</li><li>Eye injury or chemical splash</li><li>Sudden squint, double vision, or droopy eyelid</li></ul></div></section>
 <footer className="site-footer"><div><b>Dr Toshika Dahal</b><p>Pediatric Ophthalmologist and Strabismus Surgeon</p></div><p>Â© {new Date().getFullYear()} Dr Toshika Dahal. Patient education only.</p></footer></main>}

